# Generated by Django 2.0.6 on 2018-06-23 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('date_field', models.DateField(auto_now=True)),
                ('post_body', models.TextField()),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=20, unique=True)),
                ('topic', models.CharField(choices=[('TOPIC1', (('S1', 'Subtopic 1'), ('S2', 'Subtopic 2 (Default)'))), ('TOPIC2', (('S3', 'Subtopic 3'), ('S3', 'Subtopic 4'))), ('OT', 'OTHER')], default='Subtopic 2', max_length=2)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=150)),
                ('post_body', models.TextField()),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='reply',
            name='parent_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate_app.thread'),
        ),
    ]
