# Generated by Django 2.0.6 on 2018-06-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_app', '0005_auto_20180624_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reply',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
