# Generated by Django 2.1 on 2018-09-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_app', '0006_auto_20180624_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='user_name',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
