# Generated by Django 2.1 on 2018-09-28 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_app', '0007_auto_20180928_0558'),
        ('authenticate_app', '0007_auto_20180928_0608'),
    ]

    operations = [
    ]
