# Generated by Django 2.0.6 on 2018-06-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='thread',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
