# Generated by Django 2.0.6 on 2018-06-24 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_app', '0003_auto_20180624_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='post_body',
            new_name='reply_body',
        ),
    ]
